# Generated by Django 5.0.1 on 2024-02-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedperson',
            name='status',
        ),
        migrations.AlterField(
            model_name='anonymousreport',
            name='assigned_officer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='management.user'),
        ),
        migrations.AlterField(
            model_name='anonymousreport',
            name='status',
            field=models.CharField(default='Reported', max_length=255),
        ),
        migrations.AlterField(
            model_name='anonymousreport',
            name='suspect_information',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='assigned_officer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_officer', to='management.user'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='reporter_cell',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(default='Reported', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='suspect_information',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='witness_information',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
